
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    #region Data Services
    
    public sealed partial class ApplicationDataService
        : global::CMS.ApplicationData
    {
    
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        private global::CMS.Application Application
        {
            get
            {
                return global::CMS.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        private global::CMS.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::CMS.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Inserting(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Inserted(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Updating(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Updated(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Deleting(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Deleted(global::CMS.Category entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Validate(global::CMS.Category entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Single_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Single_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Single_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::CMS.Category> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Single_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::CMS.Category> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_Single_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_SingleOrDefault_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_SingleOrDefault_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_SingleOrDefault_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::CMS.Category> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_SingleOrDefault_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::CMS.Category> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_SingleOrDefault_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_All_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_All_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_All_PreprocessQuery(ref global::System.Linq.IQueryable<global::CMS.Category> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_All_Executed(global::System.Collections.Generic.IEnumerable<global::CMS.Category> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Categories_All_ExecuteFailed(global::System.Exception exception);
    
        #endregion
    
        #region Details Class
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::CMS.ApplicationDataService, global::CMS.Category>
                __CategoriesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::CMS.ApplicationDataService, global::CMS.Category>(
                    "Categories",
                    d =>
                    {
                        bool result = true;
                        d.Categories_CanInsert(ref result);
                        return result;
                    },
                    d =>
                    {
                        bool result = true;
                        d.Categories_CanUpdate(ref result);
                        return result;
                    },
                    d =>
                    {
                        bool result = true;
                        d.Categories_CanDelete(ref result);
                        return result;
                    },
                    d =>
                    {
                        bool result = true;
                        d.Categories_CanRead(ref result);
                        return result;
                    },
                    (d, e) => d.Categories_Inserting(e),
                    (d, e) => d.Categories_Inserted(e),
                    (d, e) => d.Categories_Updating(e),
                    (d, e) => d.Categories_Updated(e),
                    (d, e) => d.Categories_Deleting(e),
                    (d, e) => d.Categories_Deleted(e),
                    (d, e, r) => d.Categories_Validate(e, r));
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::CMS.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::CMS.ApplicationDataService>(
                    "SaveChanges",
                    d =>
                    {
                        bool result = true;
                        d.SaveChanges_CanExecute(ref result);
                        return result;
                    },
                    (d, args) => d.SaveChanges_Executing(),
                    (d, args) => d.SaveChanges_Executed(),
                    (d, args, ex) => d.SaveChanges_ExecuteFailed(ex));
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>
                __Categories_SingleEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>(
                    "Categories_Single",
                    d =>
                    {
                        bool result = true;
                        d.Categories_Single_CanExecute(ref result);
                        return result;
                    },
                    (d, args) => d.Categories_Single_Executing((global::System.Nullable<int>)args[0]),
                    (d, args) => d.Categories_Single_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::CMS.Category>)args[1]),
                    (d, args, ex) => d.Categories_Single_ExecuteFailed((global::System.Nullable<int>)args[0], ex),
                    (d, args) =>
                    {
                        global::System.Linq.IQueryable<global::CMS.Category> query = (global::System.Linq.IQueryable<global::CMS.Category>)args[1];
                        d.Categories_Single_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                        return query;
                    });
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>
                __Categories_SingleOrDefaultEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>(
                    "Categories_SingleOrDefault",
                    d =>
                    {
                        bool result = true;
                        d.Categories_SingleOrDefault_CanExecute(ref result);
                        return result;
                    },
                    (d, args) => d.Categories_SingleOrDefault_Executing((global::System.Nullable<int>)args[0]),
                    (d, args) => d.Categories_SingleOrDefault_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::CMS.Category>)args[1]),
                    (d, args, ex) => d.Categories_SingleOrDefault_ExecuteFailed((global::System.Nullable<int>)args[0], ex),
                    (d, args) =>
                    {
                        global::System.Linq.IQueryable<global::CMS.Category> query = (global::System.Linq.IQueryable<global::CMS.Category>)args[1];
                        d.Categories_SingleOrDefault_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                        return query;
                    });
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>
                __Categories_AllEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::CMS.ApplicationDataService>(
                    "Categories_All",
                    d =>
                    {
                        bool result = true;
                        d.Categories_All_CanExecute(ref result);
                        return result;
                    },
                    (d, args) => d.Categories_All_Executing(),
                    (d, args) => d.Categories_All_Executed((global::System.Collections.Generic.IEnumerable<global::CMS.Category>)args[0]),
                    (d, args, ex) => d.Categories_All_ExecuteFailed(ex),
                    (d, args) =>
                    {
                        global::System.Linq.IQueryable<global::CMS.Category> query = (global::System.Linq.IQueryable<global::CMS.Category>)args[0];
                        d.Categories_All_PreprocessQuery(ref query);
                        return query;
                    });
    
        }
    
        #endregion
    }
    
    #endregion
}
