
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    internal static class Application
    {
        public static global::Microsoft.LightSwitch.IApplication<global::CMS.DataWorkspace> Current
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::CMS.DataWorkspace>)global::Microsoft.LightSwitch.Framework.Base.ApplicationProvider.Current;
            }
        }
    }
}
