
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public global::CMS.ApplicationData ApplicationData
        {
            get
            {
                return global::CMS.DataWorkspace.DetailsClass.GetValue(this, global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData);
            }
        }
        
        #endregion
    
        #region Details Class
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.DataWorkspace.DetailsClass.PropertySet>
        {
            static DetailsClass()
            {
                var initializeEntry = global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::CMS.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass>
            {
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.ApplicationData> ApplicationData
                {
                    get
                    {
                        return base.GetItem(global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.ApplicationData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            internal class PropertySetProperties
            {
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.ApplicationData>.Entry ApplicationData =
                    new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.ApplicationData>.Entry(
                        "ApplicationData",
                        (d, v) => d.AddPropertyChanged(ref d._ApplicationData, v),
                        (d, v) => d.RemovePropertyChanged(ref d._ApplicationData, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData, ref d._ApplicationData, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData, ref d._ApplicationData, p, v),
                        d => d.GetValue(global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData, ref d._ApplicationData),
                        d => d.Initialize(global::CMS.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData, ref d._ApplicationData));
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::CMS.DataWorkspace, global::CMS.DataWorkspace.DetailsClass, global::CMS.ApplicationData>.Data _ApplicationData;
            
        }
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass>
    {
        #region Constructors
    
        public ApplicationData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category> Categories
        {
            get
            {
                return global::CMS.ApplicationData.DetailsClass.GetValue(this, global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories);
            }
        }
        
        #endregion
    
        #region Queries
    
        public global::CMS.Category Categories_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_Single.CreateInvocation(Id).Execute();
        }
        
        public global::CMS.Category Categories_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.ApplicationData.DetailsClass.PropertySet, global::CMS.ApplicationData.DetailsClass.MethodSet>
        {
            static DetailsClass()
            {
                var initializeMethodEntry = global::CMS.ApplicationData.DetailsClass.MethodSetProperties.Categories_Single;
                var initializePropertyEntry = global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::CMS.ApplicationData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::CMS.ApplicationData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass>
            {
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category> Categories_Single
                {
                    get
                    {
                        return base.GetItem(global::CMS.ApplicationData.DetailsClass.MethodSetProperties.Categories_Single) as global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category> Categories_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::CMS.ApplicationData.DetailsClass.MethodSetProperties.Categories_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>;
                    }
                }
                
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass>
            {
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category>> Categories
                {
                    get
                    {
                        return base.GetItem(global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category>>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            internal class MethodSetProperties
            {
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Entry Categories_Single =
                    new global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Entry(
                        "Categories_Single",
                        (d, v) => d.AddPropertyChanged(ref d._Categories_Single, v),
                        (d, v) => d.RemovePropertyChanged(ref d._Categories_Single, v),
                        true);
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Entry Categories_SingleOrDefault =
                    new global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Entry(
                        "Categories_SingleOrDefault",
                        (d, v) => d.AddPropertyChanged(ref d._Categories_SingleOrDefault, v),
                        (d, v) => d.RemovePropertyChanged(ref d._Categories_SingleOrDefault, v),
                        true);
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            internal class PropertySetProperties
            {
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category>>.Entry Categories =
                    new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category>>.Entry(
                        "Categories",
                        (d, v) => d.AddPropertyChanged(ref d._Categories, v),
                        (d, v) => d.RemovePropertyChanged(ref d._Categories, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories, ref d._Categories, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories, ref d._Categories, p, v),
                        d => d.GetValue(global::CMS.ApplicationData.DetailsClass.PropertySetProperties.Categories, ref d._Categories));
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category>>.Data _Categories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Data _Categories_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.ScalarQueryOperation<global::CMS.ApplicationData, global::CMS.ApplicationData.DetailsClass, global::CMS.Category>.Data _Categories_SingleOrDefault;
            
        }
        #endregion
    }
    
    #endregion
    
    #region Entities
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed partial class Category : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::CMS.Category, global::CMS.Category.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public Category()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public Category(global::Microsoft.LightSwitch.Framework.EntitySet<global::CMS.Category> entitySet)
            : base(entitySet)
        {
            global::CMS.Category.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::CMS.DataWorkspace> Application
        {
            get
            {
                return global::CMS.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        private global::CMS.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::CMS.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public int Id
        {
            get
            {
                return global::CMS.Category.DetailsClass.GetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::CMS.Category.DetailsClass.SetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public string Title
        {
            get
            {
                return global::CMS.Category.DetailsClass.GetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::CMS.Category.DetailsClass.SetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public int TypeId
        {
            get
            {
                return global::CMS.Category.DetailsClass.GetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.TypeId);
            }
            set
            {
                global::CMS.Category.DetailsClass.SetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeId_Changed();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public global::System.Nullable<int> ClientId
        {
            get
            {
                return global::CMS.Category.DetailsClass.GetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.ClientId);
            }
            set
            {
                global::CMS.Category.DetailsClass.SetValue(this, global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Changed();
        #endregion
    
        #region Details Class
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::CMS.Category,
                global::CMS.Category.DetailsClass,
                global::CMS.Category.DetailsClass.IImplementation,
                global::CMS.Category.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::CMS.Category, global::CMS.Category.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::CMS.Category, global::CMS.Category.DetailsClass>>
        {
            static DetailsClass()
            {
                var initializeEntry = global::CMS.Category.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::CMS.Category, global::CMS.Category.DetailsClass>.Entry
                __CategoryEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::CMS.Category, global::CMS.Category.DetailsClass>.Entry(
                    es => new Category(es),
                    e => e.Category_Created(),
                    e =>
                    {
                        bool result = false;
                        e.Category_AllowSaveWithErrors(ref result);
                        return result;
                    });
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::CMS.Category, global::CMS.Category.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::CMS.Category, global::CMS.Category.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::CMS.Category.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::CMS.Category, global::CMS.Category.DetailsClass>
            {
                 public PropertySet() : base()
                 {
                 }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::CMS.Category.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::CMS.Category.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int> TypeId
                {
                    get
                    {
                        return base.GetItem(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, global::System.Nullable<int>> ClientId
                {
                    get
                    {
                        return base.GetItem(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation
                :  global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new  int Id { get; set; }
                new  string Title { get; set; }
                new  int TypeId { get; set; }
                new  global::System.Nullable<int> ClientId { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            internal class PropertySetProperties
            {
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Entry Id =
                    new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Entry(
                        "Id",
                        (d, v) => d.AddPropertyChanged(ref d._Id, v),
                        (d, v) => d.RemovePropertyChanged(ref d._Id, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id, p, v),
                        (d, e) => d.RaiseErrorsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id, e),
                        (e, r) => e.Id_Validate(r),
                        (d, p, v) => d.InvalidateProperty(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id, p, v),
                        d => d.GetValidationResults(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id),
                        (d, v) => d.AddErrorsChanged(ref d._Id, v),
                        (d, v) => d.RemoveErrorsChanged(ref d._Id, v),
                        (d, v) => d.ImplementationEntity.Id = v,
                        e => e.Id_Changed(),
                        (d, v) => d.SetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id, v),
                        d => d.GetIsReadOnly(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id),
                        e =>
                        {
                            bool result = false;
                            e.Id_IsReadOnly(ref result);
                            return result;
                        },
                        (d, v) => d.GetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Id, v, ref d._Id),
                        d => d.GetValue(global::CMS.Category.DetailsClass.PropertySetProperties.Id, ref d._Id),
                        d => d.ImplementationEntity.Id);
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, string>.Entry Title =
                    new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, string>.Entry(
                        "Title",
                        (d, v) => d.AddPropertyChanged(ref d._Title, v),
                        (d, v) => d.RemovePropertyChanged(ref d._Title, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title, p, v),
                        (d, e) => d.RaiseErrorsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title, e),
                        (e, r) => e.Title_Validate(r),
                        (d, p, v) => d.InvalidateProperty(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title, p, v),
                        d => d.GetValidationResults(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title),
                        (d, v) => d.AddErrorsChanged(ref d._Title, v),
                        (d, v) => d.RemoveErrorsChanged(ref d._Title, v),
                        (d, v) => d.ImplementationEntity.Title = v,
                        e => e.Title_Changed(),
                        (d, v) => d.SetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title, v),
                        d => d.GetIsReadOnly(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title),
                        e =>
                        {
                            bool result = false;
                            e.Title_IsReadOnly(ref result);
                            return result;
                        },
                        (d, v) => d.GetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.Title, v, ref d._Title),
                        d => d.GetValue(global::CMS.Category.DetailsClass.PropertySetProperties.Title, ref d._Title),
                        d => d.ImplementationEntity.Title);
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Entry TypeId =
                    new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Entry(
                        "TypeId",
                        (d, v) => d.AddPropertyChanged(ref d._TypeId, v),
                        (d, v) => d.RemovePropertyChanged(ref d._TypeId, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId, p, v),
                        (d, e) => d.RaiseErrorsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId, e),
                        (e, r) => e.TypeId_Validate(r),
                        (d, p, v) => d.InvalidateProperty(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId, p, v),
                        d => d.GetValidationResults(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId),
                        (d, v) => d.AddErrorsChanged(ref d._TypeId, v),
                        (d, v) => d.RemoveErrorsChanged(ref d._TypeId, v),
                        (d, v) => d.ImplementationEntity.TypeId = v,
                        e => e.TypeId_Changed(),
                        (d, v) => d.SetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId, v),
                        d => d.GetIsReadOnly(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId),
                        e =>
                        {
                            bool result = false;
                            e.TypeId_IsReadOnly(ref result);
                            return result;
                        },
                        (d, v) => d.GetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, v, ref d._TypeId),
                        d => d.GetValue(global::CMS.Category.DetailsClass.PropertySetProperties.TypeId, ref d._TypeId),
                        d => d.ImplementationEntity.TypeId);
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, global::System.Nullable<int>>.Entry ClientId =
                    new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ClientId",
                        (d, v) => d.AddPropertyChanged(ref d._ClientId, v),
                        (d, v) => d.RemovePropertyChanged(ref d._ClientId, v),
                        (d, p) => d.RaisePropertyChanged(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId, p),
                        (d, p, v) => d.SetPendingInvoke(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId, p, v),
                        (d, e) => d.RaiseErrorsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId, e),
                        (e, r) => e.ClientId_Validate(r),
                        (d, p, v) => d.InvalidateProperty(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId, p, v),
                        d => d.GetValidationResults(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId),
                        (d, v) => d.AddErrorsChanged(ref d._ClientId, v),
                        (d, v) => d.RemoveErrorsChanged(ref d._ClientId, v),
                        (d, v) => d.ImplementationEntity.ClientId = v,
                        e => e.ClientId_Changed(),
                        (d, v) => d.SetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId, v),
                        d => d.GetIsReadOnly(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId),
                        e =>
                        {
                            bool result = false;
                            e.ClientId_IsReadOnly(ref result);
                            return result;
                        },
                        (d, v) => d.GetIsChanged(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, v, ref d._ClientId),
                        d => d.GetValue(global::CMS.Category.DetailsClass.PropertySetProperties.ClientId, ref d._ClientId),
                        d => d.ImplementationEntity.ClientId);
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, int>.Data _TypeId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::CMS.Category, global::CMS.Category.DetailsClass, global::System.Nullable<int>>.Data _ClientId;
            
        }
        #endregion
    }
    
    #endregion
    
}
